### PR TITLE
Center Visitor count

### PR DESCRIPTION
**Pull request by lsjsss**
VS Code test1 (Un code)

### CODE REVIEW

**Comment by Magi2B0y** [comment]
enhancement

**Comment by Magi2B0y** [comment]
I need more beautiful component to my profile

**Comment by Magi2B0y** [comment]
OR a star to my repository

**Comment by lsjsss** [comment]
> I need more beautiful component to my profile

Well

**Comment by Magi2B0y** [comment]
Thanks for your PR!

**Pull request merged**
